# Generated by Django 6.0.6 on 2026-07-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.IntegerField(default=0),
        ),
    ]
